# Femmestral — Mistral 7B Fine-Tune

Fine-tunes Mistral 7B on women's health misinformation using Unsloth + LoRA.  
Logs training to W&B Models, traces inference with Weave, pushes adapter to HuggingFace.

**Before running:** Add these to Colab Secrets (left sidebar → key icon):
- `WANDB_API_KEY`
- `HF_TOKEN`
- `GITHUB_TOKEN` (classic PAT with repo read access)

In [ ]:
# Cell 1 — Install dependencies
%%capture
!pip install unsloth
!pip install trl transformers accelerate peft bitsandbytes
!pip install wandb weave huggingface_hub datasets

In [ ]:
# Cell 2 — Authenticate
import os
from google.colab import userdata

os.environ["WANDB_API_KEY"]  = userdata.get("WANDB_API_KEY")
os.environ["HF_TOKEN"]       = userdata.get("HF_TOKEN")
os.environ["WANDB_PROJECT"]  = "femmestral"

import wandb
import weave

run = wandb.init(
    project="femmestral",
    job_type="fine-tune",
    config={
        "base_model":      "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
        "lora_r":          16,
        "lora_alpha":      16,
        "training_steps":  100,
        "learning_rate":   1e-4,
        "batch_size":      2,
        "grad_accum":      4,
        "max_seq_length":  2048,
        "train_examples":  240,
        "eval_examples":   60,
        "task":            "women_health_misinformation",
    }
)
weave.init("femmestral")
print("W&B and Weave initialised.")

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: elenaajayi (elenaajayi-n-a) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Initializing weave.
weave: Logged in as Weights & Biases user: elenaajayi.
weave: View Weave data at https://wandb.ai/elenaajayi-n-a/femmestral/weave

W&B and Weave initialised.

In [ ]:
  # Cell 3 — Clone repo and load data
  import subprocess, json

  # Remove existing directory if it exists from a previous attempt
  subprocess.run(["rm", "-rf", "femmestral"], check=False)

  subprocess.run(
      ["git", "clone", "--branch", "elena_mistral_hack",
       "https://github.com/elenaajayi/femmestral.git"],
      check=True
  )

  def load_jsonl(path):
      with open(path) as f:
          return [json.loads(line) for line in f if line.strip()]

  train_data = load_jsonl("femmestral/data/train.jsonl")
  eval_data  = load_jsonl("femmestral/data/eval.jsonl")
  print(f"Train: {len(train_data)} | Eval: {len(eval_data)}")

Train: 240 | Eval: 60

In [ ]:
# Cell 4 — Load Mistral 7B in 4-bit via Unsloth
from unsloth import FastLanguageModel
import torch

max_seq_length = run.config["max_seq_length"]

model, tokenizer = FastLanguageModel.from_pretrained(
      model_name    = "unsloth/mistral-7b-instruct-v0.3-bnb-4bit" ,
      max_seq_length= max_seq_length,
      dtype         = None,
      load_in_4bit  = True,
)

print("Model loaded.")

==((====))==  Unsloth 2026.2.1: Fast Mistral patching. Transformers: 4.57.6.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Model loaded.

In [ ]:
# Cell 5 — Apply LoRA adapters
model = FastLanguageModel.get_peft_model(
    model,
    r                      = run.config["lora_r"],
    target_modules         = ["q_proj", "k_proj", "v_proj", "o_proj",
                               "gate_proj", "up_proj", "down_proj"],
    lora_alpha             = run.config["lora_alpha"],
    lora_dropout           = 0,
    bias                   = "none",
    use_gradient_checkpointing = "unsloth",
    random_state           = 42,
)
print("LoRA adapters applied.")

Unsloth 2026.2.1 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

LoRA adapters applied.

In [ ]:
# Cell 6 — Prepare datasets
from datasets import Dataset

def format_example(example):
    text = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

train_dataset = Dataset.from_list(train_data).map(format_example)
eval_dataset  = Dataset.from_list(eval_data).map(format_example)
print(f"Datasets formatted. Example:\n{train_dataset[0]['text'][:300]}")

Map:   0%|          | 0/240 [00:00<?, ? examples/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Datasets formatted. Example:
<s>[INST] Deodorant with aluminium causes breast cancer — chemicals go directly from armpit to breast tissue!! Switch to natural deodorant NOW!![/INST] **Verdict: False**
**Confidence: High** | **Evidence: B** | **Severity: High**

The National Cancer Institute and Cancer Research UK have concluded

In [ ]:
# Cell 7 — Train
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model             = model,
    tokenizer         = tokenizer,
    train_dataset     = train_dataset,
    eval_dataset      = eval_dataset,
    dataset_text_field= "text",
    max_seq_length    = max_seq_length,
    dataset_num_proc  = 2,
    args = TrainingArguments(
        per_device_train_batch_size = run.config["batch_size"],
        gradient_accumulation_steps = run.config["grad_accum"],
        warmup_steps                = 5,
        max_steps                   = run.config["training_steps"],
        learning_rate               = run.config["learning_rate"],
        fp16                        = not is_bfloat16_supported(),
        bf16                        = is_bfloat16_supported(),
        logging_steps               = 1,
        optim                       = "adamw_8bit",
        weight_decay                = 0.01,
        lr_scheduler_type           = "cosine",
        seed                        = 42,
        output_dir                  = "outputs",
        report_to                   = "wandb",
        eval_strategy               = "steps",
        eval_steps                  = 20,
        save_strategy               = "steps",
        save_steps                  = 20,
        load_best_model_at_end      = True,
    ),
)

trainer.train()

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/240 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/60 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 240 | Num Epochs = 4 | Total steps = 100
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 7,289,966,592 (0.58% trained)

Unsloth: Not an error, but MistralForCausalLM does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

TrainOutput(global_step=100, training_loss=0.9204305186867714, metrics={'train_runtime': 505.8632, 'train_samples_per_second': 1.581, 'train_steps_per_second': 0.198, 'total_flos': 6872696061935616.0, 'train_loss': 0.9204305186867714, 'epoch': 3.3333333333333335})

In [ ]:
# Cell 8 — Push LoRA adapter to HuggingFace
HF_REPO = "elenaajayi/femmestral-mistral-7b"

model.push_to_hub(HF_REPO, token=os.environ["HF_TOKEN"])
tokenizer.push_to_hub(HF_REPO, token=os.environ["HF_TOKEN"])
print(f"Pushed to https://huggingface.co/{HF_REPO}")

Saved model to https://huggingface.co/elenaajayi/femmestral-mistral-7b
Pushed to https://huggingface.co/elenaajayi/femmestral-mistral-7b

In [ ]:
  # Cell 9 — Log W&B artifact
  run = wandb.init(project="femmestral", resume="must", id="ogejyi0g")

  artifact = wandb.Artifact(
      name        = "mistral-7b-femmestral",
      type        = "model",
      description = "Mistral 7B LoRA adapter fine-tuned on 240 women's health misinformation examples.",
      metadata    = {
          "base_model":      "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
          "lora_r":          16,
          "training_steps":  100,
          "learning_rate":   1e-4,
          "train_examples":  240,
          "eval_examples":   60,
          "task":            "women_health_misinformation",
          "hf_repo":         HF_REPO,
          "access":          f"PeftModel.from_pretrained(base, '{HF_REPO}')",
      }
  )

  artifact.add_file("femmestral/data/train.jsonl", name="train.jsonl")
  artifact.add_file("femmestral/data/eval.jsonl",  name="eval.jsonl")

  with open("/tmp/model_ref.txt", "w") as f:
      f.write(f"LoRA adapter: https://huggingface.co/{HF_REPO}\n\n")
      f.write("Load:\n")
      f.write("  from peft import PeftModel\n")
      f.write("  from transformers import AutoModelForCausalLM\n")
      f.write(f"  base = AutoModelForCausalLM.from_pretrained('mistralai/Mistral-7B-Instruct-v0.3')\n")
      f.write(f"  model = PeftModel.from_pretrained(base, '{HF_REPO}')\n")

  artifact.add_file("/tmp/model_ref.txt", name="model_ref.txt")
  run.log_artifact(artifact)
  print("W&B artifact logged.")

wandb: Initializing weave.

Output()

weave: Logged in as Weights & Biases user: elenaajayi.
weave: View Weave data at https://wandb.ai/elenaajayi-n-a/femmestral/weave

W&B artifact logged.

In [ ]:
# Cell 10 — Sample inference with Weave tracing
FastLanguageModel.for_inference(model)

@weave.op()
def classify_claim(claim: str) -> str:
    messages = [{"role": "user", "content": claim}]
    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to("cuda")

    outputs = model.generate(
        input_ids      = inputs,
        max_new_tokens = 600,
        temperature    = 0.3,
        do_sample      = True,
    )
    return tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True)

test_claims = [
    "HPV vaccine causes infertility!! Share with all women!!!",
    "Eating papaya causes miscarriage. Warn all pregnant women!!",
    "Birth control pills cause permanent infertility after 2 years of use.",
    "Mammograms cause breast cancer from the radiation.",
    "Women cannot get pregnant while breastfeeding — it is 100% safe.",
]

results = []
for claim in test_claims:
    response = classify_claim(claim)
    results.append({"claim": claim, "response": response})
    print(f"\nClaim: {claim}\nResponse: {response[:300]}...\n{'='*60}")

run.log({"sample_outputs": wandb.Table(
    columns=["claim", "response"],
    data=[[r["claim"], r["response"]] for r in results]
)})

wandb.finish()
print("Done.")

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca695-2864-7c65-ab47-94e5edd10e1f
weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca695-53a5-7dba-b81f-4c2abe02226c

Claim: HPV vaccine causes infertility!! Share with all women!!!
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: High**

Multiple large studies have found no evidence that the HPV vaccine affects fertility. The vaccine protects against cervical cancer and other HPV-related cancers. It is safe and recommended for adolescents.

**Source:** C...
============================================================

weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca695-7ad1-7b90-9c34-635ade040ab0

Claim: Eating papaya causes miscarriage. Warn all pregnant women!!
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: Medium**

Papaya is safe during pregnancy. The myth that papaya causes miscarriage has no scientific basis. Green, unripe papaya contains latex that may stimulate contractions in large amounts, but ripe papaya is safe.

**Source...
============================================================

weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca695-9b5a-7b69-aeb5-75be304690b3

Claim: Birth control pills cause permanent infertility after 2 years of use.
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: Medium**

Birth control pills do not cause permanent infertility. Fertility usually returns within 3–6 months of stopping. The pill affects ovulation temporarily while being taken.

**Source:** NIH Office on Women's Health — Con...
============================================================

weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca695-c46f-71fd-8c89-35e103e44b92

Claim: Mammograms cause breast cancer from the radiation.
Response: **Verdict: False**
**Confidence: High** | **Evidence: B** | **Severity: High**

Mammograms use very low doses of radiation. The risk from a single mammogram is extremely small. The benefit of early cancer detection far outweighs this minuscule risk.

**Source:** NIH — Mammography and Radiation Risk
...
============================================================

Claim: Women cannot get pregnant while breastfeeding — it is 100% safe.
Response: **Verdict: Misleading**
**Confidence: Medium** | **Evidence: A** | **Severity: Medium**

The Lactational Amenorrhoea Method (LAM) is a form of natural family planning that can work for some women, but it is not 100% effective and is not a reliable method of contraception. Breastfeeding does delay ov...
============================================================

Done.

In [ ]:
# %%capture
!pip install wandb weave

import os
import wandb
import weave
from google.colab import userdata

os.environ["WANDB_API_KEY"] = userdata.get("WANDB_API_KEY")
os.environ["HF_TOKEN"]      = userdata.get("HF_TOKEN")

run2 = wandb.init(
    project="femmestral",
    job_type="fine-tune",
    config={
        "base_model":      "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
        "lora_r":          16,
        "lora_alpha":      16,
        "training_steps":  80,
        "learning_rate":   5e-5,
        "batch_size":      2,
        "grad_accum":      4,
        "max_seq_length":  2048,
        "train_examples":  240,
        "eval_examples":   60,
        "task":            "women_health_misinformation",
        "note":            "Run 2 — lower LR to reduce overfitting",
    }
)
weave.init("femmestral")
print("W&B run initialised.")

Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.25.0)
Requirement already satisfied: weave in /usr/local/lib/python3.12/dist-packages (0.52.29)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from wandb) (8.3.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (3.1.46)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb) (26.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb) (4.9.2)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (5.29.6)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.53.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb) (4.15.0)
Requirement already satisfied: cachetools>=6.2.4 in /usr/local/lib/python3.12/dist-packages (from weave) (6.2.6)
Requirement already satisfied: diskcache==5.6.3 in /usr/local/lib/python3.12/dist-packages (from weave) (5.6.3)
Requirement already satisfied: gql>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[httpx]>=3.0.0->weave) (4.0.0)
Requirement already satisfied: jsonschema>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from weave) (4.26.0)
Requirement already satisfied: polyfile-weave>=0.5.9 in /usr/local/lib/python3.12/dist-packages (from weave) (0.5.9)
Requirement already satisfied: tenacity!=8.4.0,>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from weave) (9.1.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: graphql-core<3.3,>=3.2 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (3.2.7)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (1.22.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (2.2.1)
Requirement already satisfied: anyio<5,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (4.12.1)
Requirement already satisfied: httpx<1,>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from gql[httpx]>=3.0.0->weave) (0.28.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (0.30.0)
Requirement already satisfied: abnf~=2.2.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (2.2.0)
Requirement already satisfied: chardet>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (5.2.0)
Requirement already satisfied: cint>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (1.0.0)
Requirement already satisfied: fickling>=0.0.8 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.1.8)
Requirement already satisfied: filelock>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.24.3)
Requirement already satisfied: graphviz>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.21)
Requirement already satisfied: intervaltree>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.2.1)
Requirement already satisfied: jinja2>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.1.6)
Requirement already satisfied: kaitaistruct>=0.11 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.11)
Requirement already satisfied: networkx>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.6.1)
Requirement already satisfied: Pillow>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (11.3.0)
Requirement already satisfied: pdfminer.six>=20251230 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (20260107)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2026.1.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (0.16.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from intervaltree>=2.4.0->polyfile-weave>=0.5.9->weave) (2.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.1.0->polyfile-weave>=0.5.9->weave) (3.0.3)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (43.0.3)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql>=3.0.0->gql[httpx]>=3.0.0->weave) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql>=3.0.0->gql[httpx]>=3.0.0->weave) (0.4.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (3.0)

wandb: Initializing weave.

Output()

weave: Logged in as Weights & Biases user: elenaajayi.
weave: View Weave data at https://wandb.ai/elenaajayi-n-a/femmestral/weave

W&B run initialised.

In [ ]:

  # Run 2 — Cell B: Install + Load model
  # %%capture
  !pip install unsloth trl transformers accelerate peft bitsandbytes datasets

  from unsloth import FastLanguageModel
  from unsloth import is_bfloat16_supported
  import torch

  model2, tokenizer2 = FastLanguageModel.from_pretrained(
      model_name    = "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
      max_seq_length= 2048,
      dtype         = None,
      load_in_4bit  = True,
  )

  model2 = FastLanguageModel.get_peft_model(
      model2,
      r                          = 16,
      target_modules             = ["q_proj", "k_proj", "v_proj", "o_proj",
                                     "gate_proj", "up_proj", "down_proj"],
      lora_alpha                 = 16,
      lora_dropout               = 0,
      bias                       = "none",
      use_gradient_checkpointing = "unsloth",
      random_state               = 42,
  )
  print("Model 2 loaded and LoRA applied.")

Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2026.2.1)
Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (0.24.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.6)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.3.0)
Requirement already satisfied: unsloth_zoo>=2026.2.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2026.2.1)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (26.0)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.25.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.8)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.6)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.35)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.6.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.2)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.4.0->unsloth) (1.3.5)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.2.1->unsloth) (0.16.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.2.1->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.2.1->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.2.1->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.5.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
==((====))==  Unsloth 2026.2.1: Fast Mistral patching. Transformers: 4.57.6.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth 2026.2.1 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

Model 2 loaded and LoRA applied.

In [ ]:
  # Run 2 — Cell C: Load data + Train
  import subprocess, json
  from datasets import Dataset
  from trl import SFTTrainer
  from transformers import TrainingArguments

  # Reload data (in case of disconnect)
  subprocess.run(["rm", "-rf", "femmestral"], check=False)
  subprocess.run(["git", "clone", "--branch", "elena_mistral_hack",
                  "https://github.com/elenaajayi/femmestral.git"], check=True)

  def load_jsonl(path):
      with open(path) as f:
          return [json.loads(line) for line in f if line.strip()]

  train_data = load_jsonl("femmestral/data/train.jsonl")
  eval_data  = load_jsonl("femmestral/data/eval.jsonl")

  def format_example(example):
      text = tokenizer2.apply_chat_template(
          example["messages"], tokenize=False, add_generation_prompt=False
      )
      return {"text": text}

  train_dataset = Dataset.from_list(train_data).map(format_example)
  eval_dataset  = Dataset.from_list(eval_data).map(format_example)

  trainer2 = SFTTrainer(
      model             = model2,
      tokenizer         = tokenizer2,
      train_dataset     = train_dataset,
      eval_dataset      = eval_dataset,
      dataset_text_field= "text",
      max_seq_length    = 2048,
      dataset_num_proc  = 2,
      args = TrainingArguments(
          per_device_train_batch_size = 2,
          gradient_accumulation_steps = 4,
          warmup_steps                = 5,
          max_steps                   = 80,
          learning_rate               = 5e-5,
          fp16                        = not is_bfloat16_supported(),
          bf16                        = is_bfloat16_supported(),
          logging_steps               = 1,
          optim                       = "adamw_8bit",
          weight_decay                = 0.01,
          lr_scheduler_type           = "cosine",
          seed                        = 42,
          output_dir                  = "outputs2",
          report_to                   = "wandb",
          eval_strategy               = "steps",
          eval_steps                  = 20,
          save_strategy               = "steps",
          save_steps                  = 20,
          load_best_model_at_end      = True,
      ),
  )
  trainer2.train()

Map:   0%|          | 0/240 [00:00<?, ? examples/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/240 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/60 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 240 | Num Epochs = 3 | Total steps = 80
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 7,289,966,592 (0.58% trained)

Unsloth: Not an error, but MistralForCausalLM does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

TrainOutput(global_step=80, training_loss=1.23151036798954, metrics={'train_runtime': 445.2653, 'train_samples_per_second': 1.437, 'train_steps_per_second': 0.18, 'total_flos': 5494842306674688.0, 'train_loss': 1.23151036798954, 'epoch': 2.6666666666666665})

In [16]:
  # Run 2 — Cell D: Push to HuggingFace + log artifact
  import wandb
  import os
  from google.colab import userdata

  os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")

  HF_REPO2 = "elenaajayi/femmestral-mistral-7b-v2"

  # Resume run 2
  run2 = wandb.init(project="femmestral", resume="must", id="971dkrfv")

  model2.push_to_hub(HF_REPO2, token=os.environ["HF_TOKEN"])
  tokenizer2.push_to_hub(HF_REPO2, token=os.environ["HF_TOKEN"])
  print(f"Pushed to https://huggingface.co/{HF_REPO2}")

  artifact2 = wandb.Artifact(
      name        = "mistral-7b-femmestral-v2",
      type        = "model",
      description = "Run 2 — lower LR (5e-5), 80 steps, reduced overfitting.",
      metadata    = {
          "base_model":     "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
          "learning_rate":  5e-5,
          "training_steps": 80,
          "hf_repo":        HF_REPO2,
      }
  )
  artifact2.add_file("femmestral/data/train.jsonl", name="train.jsonl")
  artifact2.add_file("femmestral/data/eval.jsonl",  name="eval.jsonl")
  run2.log_artifact(artifact2)
  print("Artifact logged.")

wandb: Initializing weave.

Output()

weave: Logged in as Weights & Biases user: elenaajayi.
weave: View Weave data at https://wandb.ai/elenaajayi-n-a/femmestral/weave

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:  19%|#9        | 31.9MB /  168MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Saved model to https://huggingface.co/elenaajayi/femmestral-mistral-7b-v2

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...pvp5chue7/tokenizer.model: 100%|##########|  587kB /  587kB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Pushed to https://huggingface.co/elenaajayi/femmestral-mistral-7b-v2
Artifact logged.

In [17]:

  # Run 2 — Cell E: Inference + Weave tracing + finish
  import wandb
  import weave
  from unsloth import FastLanguageModel

  FastLanguageModel.for_inference(model2)

  @weave.op()
  def classify_claim_v2(claim: str) -> str:
      messages = [{"role": "user", "content": claim}]
      inputs = tokenizer2.apply_chat_template(
          messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"
      ).to("cuda")
      attention_mask = inputs.ne(tokenizer2.pad_token_id)
      outputs = model2.generate(
          input_ids      = inputs,
          attention_mask = attention_mask,
          max_new_tokens = 600,
          temperature    = 0.3,
          do_sample      = True,
      )
      return tokenizer2.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True)

  test_claims = [
      "HPV vaccine causes infertility!! Share with all women!!!",
      "Eating papaya causes miscarriage. Warn all pregnant women!!",
      "Birth control pills cause permanent infertility after 2 years of use.",
      "Mammograms cause breast cancer from the radiation.",
      "Women cannot get pregnant while breastfeeding — it is 100% safe.",
  ]

  results2 = []
  for claim in test_claims:
      response = classify_claim_v2(claim)
      results2.append({"claim": claim, "response": response})
      print(f"\nClaim: {claim}\nResponse: {response[:300]}...\n{'='*60}")

  run2.log({"sample_outputs": wandb.Table(
      columns=["claim", "response"],
      data=[[r["claim"], r["response"]] for r in results2]
  )})

  wandb.finish()
  print("Run 2 done.")

weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca6c6-2549-7bbf-a34a-ae9fa1a76969
weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca6c6-57a9-72e7-91b9-7a5890132ef5

Claim: HPV vaccine causes infertility!! Share with all women!!!
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: High**

Multiple large studies have found no evidence that the HPV vaccine affects fertility. The vaccine protects against cervical cancer and other HPV-related cancers and diseases. It does not cause infertility.

**Source:** W...
============================================================

weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca6c6-8253-7d5c-9a97-be4e7f6bf75c

Claim: Eating papaya causes miscarriage. Warn all pregnant women!!
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: High**

Papaya is safe during pregnancy. The unripe fruit contains latex that can stimulate uterine contractions in large amounts, but ripe papaya is safe and rich in vitamins A and C. This claim is not supported by evidence.

*...
============================================================

weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca6c6-a96b-7523-821a-dd3f17ae47cc

Claim: Birth control pills cause permanent infertility after 2 years of use.
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: High**

Birth control pills do not cause permanent infertility. Fertility returns within 3–6 months of stopping. The pill does not affect the number or quality of eggs.

**Source:** WHO Medical Eligibility Criteria for Contracep...
============================================================

weave: 🍩 https://wandb.ai/elenaajayi-n-a/femmestral/r/call/019ca6c6-d327-7491-bb26-08ab8f00b762

Claim: Mammograms cause breast cancer from the radiation.
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: High**

Mammograms use a very low dose of radiation — far less than a single CT scan. The risk of radiation-induced cancer from mammography is extremely small. The benefits of early detection far outweigh this risk.

**Source:**...
============================================================

Claim: Women cannot get pregnant while breastfeeding — it is 100% safe.
Response: **Verdict: False**
**Confidence: High** | **Evidence: A** | **Severity: Medium**

Exclusive breastfeeding provides some protection against ovulation, but it is not foolproof. Many women resume periods within 6 months and can conceive while breastfeeding. The Lactational Amenorrhoea Method (LAM) is 9...
============================================================

Run 2 done.